### ISSUE TITLE
Add `output_schema` to SAML. 

### ISSUE THREAD

**Issue by homanp** [superagent-ai/superagent#918]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

If a agent yaml node includes `output_schema` we should add a parsing agent as the last step in a workflow. 
This parsing agent takes the `output_schema` content as it's prompt return a structured object. This agent could just be a simple call to OpenAI. 

Example SAML: 

```yaml
workflows:
  - superagent:
       name: test
       llm: gpt-3.5-turbo-0125
       prompt: Hello 
       output_schema: 
         - my_key: string
         - my_second_key: number
```

This should support common types such as `enum`, `number` and `string`. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.
