### ISSUE TITLE
[brainstorming] Adding image generation models as a type of agent??

### ISSUE THREAD

**Issue by elisalimli** [superagent-ai/superagent#964]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I think about adding image generation models as a new type of agent. 

For instance: 

```yaml
workflows:
  - bedrock:
      model: bedrock/stability.stable-diffusion-xl-v0
      name: Image generator assistant
      intro: 👋 Hi there! How can I help search for answers on the internet.
```

Adding this as a new tool is another option, but I think it does not make sense to call an LLM inference API to call the tool. If we want to generate an image, it is always the case that we will choose that image gen tool. So, it would cause extra latency + cost. That's why I think adding image gen as a agent type is more viable option.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.
